site_name: "Krupy Templates Extensions"
site_description: "Special Jinja2 extension for Krupy that allows to load extensions using file paths relative to the template root instead of Python dotted paths."
site_url: "https://krunal-kevadiya.github.io/krupy-templates-extensions"
repo_url: "https://krunal-kevadiya.github.io/krupy-templates-extensions"
repo_name: "Krunal-Kevadiya/krupy-templates-extensions"
watch: [src]

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
#- Author's website: https://krunal-kevadiya.github.io/

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.top
    - navigation.
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji
  - pymdownx.magiclink
  - toc:
      permalink: true
  - footnotes

plugins:
  - autorefs
  - search
  - markdown-exec
  - mkdocstrings
